name: hello-world 
on: push
jobs:
  hello-world-job:
    runs: ubuntu-latest
    steps:
      -name: Check out respository code 
       uses: actions/checkout@V3
      -run: echo"$(cat hello_world.txt)"
